const AZURE_SERVERLESS_API = "https://post-push.azurewebsites.net"
const CLUBTAL_SERVICES_API = "https://clubtal-web-services.azurewebsites.net"
const EMAIL_SERVICE_GENERAL_ENDPOINT = "/api/EmailService"
const EMAIL_SERVICE_RECRUIT_ENDPOINT = "/api/EmailServiceRecruit1"
const COMUNICATE_CHAT_BOT_ENDPOINT = "/api/comunicate-chat-bot"
const CREATE_MAGIC_LINK_ENDPOINT = "/api/create-magic-link"
const CERTIFY_MAGIC_LINK_ENDPOINT = "/api/certify-magic-link"
const SEND_FEEDBACK_EMAIL_ENDPOINT = "/api/send-feedback-email"
const GET_TEXT_ANALYSIS_ENDPOINT = "/api/get-text-analysis"


export const EMAIL_SERVICE_GENERAL = `${AZURE_SERVERLESS_API}${EMAIL_SERVICE_GENERAL_ENDPOINT}`
export const EMAIL_SERVICE_RECRUIT = `${AZURE_SERVERLESS_API}${EMAIL_SERVICE_RECRUIT_ENDPOINT}`
export const COMUNICATE_CHAT_BOT = `${CLUBTAL_SERVICES_API}${COMUNICATE_CHAT_BOT_ENDPOINT}`
export const CREATE_MAGIC_LINK = `${CLUBTAL_SERVICES_API}${CREATE_MAGIC_LINK_ENDPOINT}`
export const CERTIFY_MAGIC_LINK = `${CLUBTAL_SERVICES_API}${CERTIFY_MAGIC_LINK_ENDPOINT}`
export const GET_TEXT_ANALYSIS = `${CLUBTAL_SERVICES_API}${GET_TEXT_ANALYSIS_ENDPOINT}`
export const SEND_FEEDBACK_EMAIL = `${AZURE_SERVERLESS_API}${SEND_FEEDBACK_EMAIL_ENDPOINT}`