const AZURE_SERVERLESS_API = "https://post-push.azurewebsites.net"
const EMAIL_SERVICE_GENERAL_ENDPOINT = "/api/EmailService"
const EMAIL_SERVICE_RECRUIT_ENDPOINT = "/api/EmailServiceRecruit1"

export const EMAIL_SERVICE_GENERAL = `${AZURE_SERVERLESS_API}${EMAIL_SERVICE_GENERAL_ENDPOINT}`
export const EMAIL_SERVICE_RECRUIT = `${AZURE_SERVERLESS_API}${EMAIL_SERVICE_RECRUIT_ENDPOINT}`
